var webpack=require("webpack");
var HtmlWebpackPlugin=require("html-webpack-plugin");
module.exports={
    entry:__dirname+"/src/main.js",
    output:{
        path:__dirname+"/dist",
        filename:"[name].js"
    },
    module:{
        rules:[
            {
                test:/\.js$/,
                loader:"babel-loader"
            },
            {
                test:/\.vue$/,
                loader:"vue-loader"
            },
            {
                test:/\.html$/,
                loader:"html-loader"
            },
            {
                test:/\.css$/,
                use:["style-loader","css-loader"]
            },
            {
                test:/\.jpg|.png$/,
                loader:"url-loader"
            }
        ]
    },
    resolve:{
        alias:{
            "vue":"vue/dist/vue.js"
        }
    },
    devServer:{
        port:8080,
        host:"localhost",
        hot:true,
        setup(app){
            app.get("/some",function(req,res){
                res.json( [
                    {
                        bac:"#B8DCB1",
                        txt:"音乐",
                        icon:"&#xe68e;"
                    },
                    {
                        bac:"#D9B598",
                        txt:"历史",
                        icon:"&#xe68e;"
                    },
                    {
                        bac:"#B59AF7",
                        txt:"情感生活",
                        icon:"&#xe68e;"
                    },
                    {
                        bac:"#F1D784",
                        txt:"人文",
                        icon:"&#xe68e;"
                    },
                        {
                        bac:"#E6DEB2",
                        txt:"付费精品",
                        icon:"&#xe68e;"
                    },
                        {
                        bac:"#93E8DE",
                        txt:"脱口秀",
                        icon:"&#xe68e;"
                    },
                        {
                        bac:"#F798BA",
                        txt:"娱乐",
                        icon:"&#xe68e;"
                    },
                        {
                        bac:"#99EEEA",
                        txt:"英语",
                        icon:"&#xe68e;"
                    },
                        {
                        bac:"#73A0E3",
                        txt:"教育培训",
                        icon:"&#xe68e;"
                    },
                        {
                        bac:"#A2D3F1",
                        txt:"小语种",
                        icon:"&#xe68e;"
                    },
                        {
                        bac:"#8EB5F7",
                        txt:"商业财经",
                        icon:"&#xe68e;"
                    },
                        {
                        bac:"#F19296",
                        txt:"健康养牛",
                        icon:"&#xe68e;"
                    },
                        {
                        bac:"#BAECF3",
                        txt:"国学书院",
                        icon:"&#xe68e;"
                    },
                        {
                        bac:"#FC888D",
                        txt:"3D体验馆",
                        icon:"&#xe68e;"
                    },
                        {
                        bac:"#79B0EA",
                        txt:"头条",
                        icon:"&#xe68e;"
                    },
                        {
                        bac:"#EDA785",
                        txt:"广播剧",
                        icon:"&#xe68e;"
                    }

                ])
            })
        }
    },
    plugins:[
        new webpack.optimize.UglifyJsPlugin(),
        new webpack.HotModuleReplacementPlugin(),
        new HtmlWebpackPlugin({
            template:"./index.html"
        })
    ]
}